import sys

def some_really_long_function_name_that_will_hopefully_trigger_a_linter_violation_so_i_can_see_hound_python_working_in_real_life_but_like_digital_internet_life():
    print('hi')

some_really_long_function_name_that_will_hopefully_trigger_a_linter_violation_so_i_can_see_hound_python_working_in_real_life_but_like_digital_internet_life()
